spring.application.name=bookingservice
server.port=8081
inventory.service.url=http://localhost:8080/api/v1/inventory/events

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket
spring.datasource.username=postgres
spring.datasource.password=seng12
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Configuration
# keep your existing bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# producer serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# optional: cleaner payload headers
spring.kafka.properties.spring.json.add.type.headers=true

# keep topic naming consistent
spring.kafka.template.default-topic=booking
spring.kafka.producer.retries=1
spring.kafka.producer.retry-backoff-ms=100
spring.kafka.producer.acks=1
spring.kafka.producer.request-timeout-ms=5000
spring.kafka.producer.delivery-timeout-ms=10000
spring.kafka.properties.connections.max.idle.ms=9000
spring.kafka.properties.reconnect.backoff.ms=100
spring.kafka.properties.reconnect.backoff.max.ms=1000